### ISSUE TITLE
Upload the library to PyPI

### ISSUE THREAD

**Issue by bryant1410** [tfmoraes/python-casmoothing#1]
I think it would be nice to have this library on PyPI, to be able to simply do the following:

```bash
pip install casmoothing
```

**Comment by tfmoraes** [comment]
This library is not necessary anymore to run InVesalius. Furthermore, this library depends on VTK, which is not available in PyPI.

**Comment by bryant1410** [comment]
And what about PyVTK?

**Comment by tfmoraes** [comment]
PyVTK only provides the creation of VTK files. It's not a complete VTK. PyVTK doesn't cover all our necessities. We use VTK in InVesalius to render, create meshes (via Marching Cubes) and other algorithms.

**Comment by bryant1410** [comment]
Oh, I see.

**Comment by bryant1410** [comment]
There's an issue regarding this: https://gitlab.kitware.com/vtk/vtk-superbuild/issues/2

**Comment by tfmoraes** [comment]
It would be very helpful if they add VTK to Pypi.
