### ISSUE TITLE
Segfaults at import

### ISSUE THREAD

**Issue by tillea** [tfmoraes/python-casmoothing#2]
Hi Thiago,
I stumbled upon a [message on Debian devel list](https://lists.debian.org/debian-devel/2018/04/msg00258.html) which also lists the package python-casmoothing.  I just tested

    $ python 
    Python 2.7.14+ (default, Apr  2 2018, 04:16:25) 
    [GCC 7.3.0] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import ca_smoothing
    Speicherzugriffsfehler

(sorry for German message - I tried to set my environment to en but failed).
I'm using the Debian package maintained by you (which was moved to [Git](https://salsa.debian.org/med-team/python-casmoothing).  Can you please have a look?
BTW, it seems it is time to move to Python3.
Kind regards, Andreas.

**Comment by tfmoraes** [comment]
Hi @tillea ,

Thanks for the bug report. But python-casmoothing is not necessary anymore. I implemented the functionality of python-casmoothing inside InVesalius using Cython. I don' t know if I need to do something, but I think python-casmoothing have to be removed from Debian repository.

Yeah, we have to move inVesalius to Python3.

Best regards.

**Comment by tillea** [comment]
I've asked for [removal from Debian](https://bugs.debian.org/895877)

**Comment by ghost** [comment]
Hi @tfmoraes , i just fixed a whole hour the Cmake list of casmoothing 
would you please edit the dependencies on the https://github.com/invesalius/invesalius3/wiki/Running-InVesalius-3-in-Linux wiki page, to not include python-casmoothing? I build on arch, and translated the debian to arch dependencies. Your comment above states that the smoothing is included in invesalius3 itself. Thanks for your help. And also, much OT: can i setup.py Invesalius just without pip dependencies?

**Comment by tfmoraes** [comment]
Hi @chlorophyll-zz , done! Also, I've added the steps to make InVesalius run with WXPython4 in Ubuntu 18.04. The dependencies you need to setup.py InVesalius ( `python setup.py build_ext --inplace`) are Numpy and Cython (see the field Build-Depends on [debian/control](https://salsa.debian.org/med-team/invesalius/blob/master/debian/control)).

If you are using the HEAD version from invesalius github, you can use Python3. But just make sure you have VTK and vtkgdcm compiled to Python3.
